apiVersion: v1 # this kube-apiserver version to req pod
kind: Pod # requesting for POD only 
metadata: # info about pod 
 name: narsing-123  # name of my POD 
spec: 
 containers:
 - image: narsingshah/httpd:shah1 # docker image from Docker hub 
   name: shah-web # name of the container 
   ports: # optional field 
   - containerPort: 80 # port of application running in container
